### ISSUE TITLE
add link to get started guide to docs page

### ISSUE THREAD

**Issue by k2s** [senecajs/senecajs.org#254]
the page http://senecajs.org/get-started/ is not listed in http://senecajs.org/docs/

**Comment by mcdonnelldean** [comment]
This is a bug. We are flattening down the website a bit to get nicer urls. Should be fixed before tomorrow.

**Comment by matiger** [comment]
Is this fixed? Cant see the get-started page...

**Comment by k2s** [comment]
it is not fixed, use http://senecajs.org/docs/tutorials/getting-started.html (from #253)

**Comment by matiger** [comment]
thanks :+1:

**Comment by mcdonnelldean** [comment]
This has now been corrected. The live link is http://senecajs.org/getting-started/ and the button on the landing page is now corrected too. Closed via #255

**Comment by k2s** [comment]
1. I would appreciate if you would add the `getting-started` link to be on top of http://senecajs.org/docs/

2. also the link `Documentation` on  bottom of http://senecajs.org/docs/ is pointing to http://senecajs.org/tutorials/ which is 404. Maybe it should point to http://senecajs.org/docs/ ?

thx

**Comment by mcdonnelldean** [comment]
Good points I'll do these this afternoon

Kindest Regards,

Dean

On 19 Aug 2016, at 15:26, k2s <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  I would appreciate if you would add the getting-started link to be on top of http://senecajs.org/docs/

  2.  also the link Documentation on bottom of http://senecajs.org/docs/ is pointing to http://senecajs.org/tutorials/ which is 404. Maybe it should point to http://senecajs.org/docs/ ?

thx

-
